# Site settings
title: Jennifer Sadler
description: PhD candidate researching eating behavior
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://jennyrsadler.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jennifer Sadler
user_description: I'm a PhD Candidate in the department of Nutrition at the University of North Carolina at Chapel Hill. I study how we form eating habits using psychology, neuroscience, and cognitive science approaches. I'm interested in how food preferences, both for and against foods, affect eating habits and health. Ask me about open science. Check out my publications on  <a href="https://scholar.google.com/citations?user=A-248aEAAAAJ&hl=en" target="_blank">Google Scholar</a>
user_title: PhD candidate researching eating behavior
email: jen.r.sadler@gmail.com
# twitter_username: jennysad9
# github_username:  jennyrsadler
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
